USE alx_book_store;

CREATE TABLE IF NOT EXISTS AUTHORS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    BIO TEXT
);

CREATE TABLE IF NOT EXISTS BOOKS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    AUTHOR_ID INT,
    PUBLISHED_YEAR YEAR,
    PRICE DECIMAL(8, 2),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID)
);

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE VARCHAR(20),
    ADDRESS TEXT
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    ORDER_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);

CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    QUANTITY INT DEFAULT 1,
    PRICE DECIMAL(8, 2),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID)
);

